ALTER TABLE vendors
  ADD COLUMN IF NOT EXISTS owner_name VARCHAR(150),
  ADD COLUMN IF NOT EXISTS business_address TEXT,
  ADD COLUMN IF NOT EXISTS pan_number VARCHAR(20),
  ADD COLUMN IF NOT EXISTS fssai_license VARCHAR(40);
